version: "3"

services:
  proxy:
    image: nginx:latest
    restart: always
    links:
        - apache
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80

  apache:
    build: apache/
    restart: always
